sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t anujjaryal/react-test -f ./client/Dockerfile ././client/Dockerfile

script:
  - docker run -e CI=true anujjaryal/react-test npm test

after_success: 
  - docker build -t anujjaryal/multi-client ./client
  - docker build -t anujjaryal/multi-nginx ./nginx
  - docker build -t anujjaryal/multi-server ./server
  - docker build -t anujjaryal/multi-worker ./worker
