version: '3'
services:
  nginx:
    image: anujjaryal/multi-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
  server:
    image: anujjaryal/multi-server
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: anujjaryal/multi-client
    mem_limit: 128m
    hostname: client
  worker:
    image: anujjaryal/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT